---
- name: Add Hashicorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.asc

- name: Add Hashicorp apt repository
  ansible.builtin.apt_repository:
    filename: hashicorp
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.asc] {{ hashi_common__apt_repo }} {{ ansible_distribution_release }} main
    state: present
